/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.rutesh.microservices.api.core.recommendation;

import spock.lang.Specification

class RecommendationTest extends Specification {
    /*def "someLibraryMethod returns true"() {
        setup:
        def lib = new Library()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }*/
}
